layout_spectrum: 0.18879515654407442
typography_spectrum: 0.8269678798969835
color:
  brandColors:
    - '#FEFFF7'
    - '#212349'
    - '#FF934B'
    - '#975968'
    - '#A38ED3'
  brandStrength: 0.23686929536052048
  lightness: 0.8526741252280772
  saturation: 0.5453841001726687
  rhythmicContrast: 0.429470919072628
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Barry Executives
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Barry Executives
description: '"placements through partnerships"'
purpose: []
