typography_spectrum: 0.6709
color:
  brandColors:
    - '#fefff7'
    - '#212349'
    - '#ff934b'
    - '#975968'
    - '#a38ed3'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74592
analytics:
  google: null
  facebook: null
  twitter: null
name: Barry Executives
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: >-
      ABOUT US(like you really care. Just get me a great job, great money &
      career prospects, or the partner will leave me,.... fact....)
    id: 333e6963-1c35-4730-bbaa-bba490d712f1
    type: content
favicon: null
title: placements through partnerships
purpose: []
