name: Barry Executives
favicon: null
layout_spectrum: 0.50921
typography_spectrum: 0.6709
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#08fdfe'
    - '#03326a'
    - '#006cd7'
    - '#95fdfa'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
