name: Barry Executives
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4c5171'
    - '#4a8ea5'
    - '#a1af96'
    - '#282f42'
  brandStrength: 0.892368751578033
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.26216990663670003
purpose: []
