name: Barry Executives
favicon: null
layout_spectrum: 0.50921
typography_spectrum: 1
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aefefd'
    - '#00000c'
    - '#71965c'
    - '#68cefe'
    - '#0d381a'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
