layout_spectrum: 0.4325401275418699
typography_spectrum: 0.4454685118980706
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.8545260976534337
  lightness: 0.16692595439963043
  saturation: 0.7286612610332668
  rhythmicContrast: 0.6586823922116309
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Barry Executives
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Barry Executives
description: '"placements through partnerships"'
purpose: []
