name: Barry Executives
favicon: null
layout_spectrum: 0.50921
typography_spectrum: 0.6709
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0000'
    - '#e8c164'
    - '#b75a26'
    - '#57493e'
    - '#fef4df'
  brandStrength: 0.1875
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
