name: Barry Executives
favicon: null
layout_spectrum: 0.50921
typography_spectrum: 0.6709
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#68cae9'
    - '#feffff'
    - '#aceffd'
    - '#00ffff'
    - '#558899'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
