name: Barry Executives
favicon: null
layout_spectrum: 0
typography_spectrum: 0.71411
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4c5171'
    - '#4a8ea5'
    - '#a1af96'
    - '#282f42'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
